# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/ilitek9881h/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/

obj-y	+=  ilitek_spi.o
obj-y	+=  ilitek_touch.o
obj-y	+=  ilitek_plat_mtk.o
obj-y	+=  ilitek_main.o
obj-y	+=  ilitek_mp.o
obj-y	+=  ilitek_node.o
obj-y   +=  ilitek_ic.o
obj-y   +=  ilitek_hostdl.o
