#ifdef VENDOR_EDIT
#HANG_OPPO_ALL
#Kun Hu@TECH.BSP.Stability.PROJECT_PHOENIX, 2019/06/08, Remove phoenix for Self Stability Test Version
ifneq ($(SPECIAL_OPPO_CONFIG),1)
obj-y += phoenix_base.o
obj-y += phoenix_dump.o
#//Bright.Zhang@PSW.TECH 2018/12/24, Add phenix base
obj-y += monitor_bootup.o
endif
#endif /* VENDOR_EDIT */


