#
# ODM_HQ_EDIT
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += nt36525b_hdp_dsi_vdo_djn_al2350.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
